---
name: test
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/*.yaml
  # pull_request:
  #   paths:
  #     - .github/workflows/*.yaml
  #     - .config/aqua/imports/actionlint.yaml
  #     - .config/aqua/imports/reviewdog.yaml
jobs:
  actionlint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # For reviewdog
      contents: read # For checkout private repository
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0
      - uses: aquaproj/aqua-installer@294926f94b4233f202a2f03875c604f840cfed70 # v2.1.1
        with:
          aqua_version: v2.8.0
        env:
          AQUA_CONFIG: ./.config/aqua/aqua.yaml
      - name:
        run: ls -la
