---
name: test
on: pull_request
permissions: {}
jobs:
  path-filter:
    # Get changed files to filter jobs
    outputs:
      renovate-config-validator: ${{steps.changes.outputs.renovate-config-validator}}
      ghalint: ${{steps.changes.outputs.ghalint}}
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50 # v2.11.1
        id: changes
        with:
          filters: |
            renovate-config-validator:
              - renovate.json
              - .github/workflows/test.yaml
            ghalint:
              - .github/workflows/*.yaml
              - aqua/aqua.yaml
              - aqua/imports/ghalint.yaml
              - ghalint.yaml
  
  status-check:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - run: exit 1
    if: failure()
    needs:
      - renovate-config-validator
      - ghalint

  renovate-config-validator:
    uses: suzuki-shunsuke/renovate-config-validator-workflow/.github/workflows/validate.yaml@1a2fd7b15d99b1c434124b0bd2d8bd55b54ed869 # v0.2.0
    permissions:
      contents: read
    needs: path-filter
    if: needs.path-filter.outputs.renovate-config-validator == 'true'

  ghalint:
    needs: path-filter
    if: needs.path-filter.outputs.ghalint == 'true'
    uses: ./.github/workflows/wc-ghalint.yaml
    permissions: {}
